### PR TITLE
ttools: Allow tabletest.py to run standalone

### PR DESCRIPTION
**Pull request by olebole**
This patch adjust `tabletest.py` so that it may run directly from jython (if all paths are set accordingly). In this case, the standard method  `unittest.main()` is called instead of `TableTest().runTests()`. The latter is still needed if `tabletest.py` is run from `JyStiltsTest.java`. The choice is made by the `testdir` global variable that is preset from `JyStiltsTest`. If it is not set, we assume the data file `messier.xml` in the same directory as the script.

### CODE REVIEW

**Comment by mbtaylor** [comment]
No good - if I invoke the unit tests from the ant target, most conveniently like this:

    ant -Dtestcase=uk.ac.starlink.ttools.JyStiltsTest run-single-test

these tests just don't run.  In that context it seems that `__name__ == '__main__'` is false, `__name__` seems to be `'main'` instead.  I don't know enough about [py]thon invocation contexts to know how robust that is.  If non-bulletproof invocation logic like this remains in the `tabletest.py` file it would be nice to have something in the unit test that checks the tests have actually been run to catch this sort of thing in the future.

**Comment by olebole** [comment]
I changed now the invocation logic at the end so that the existence of a `testdir` global will unconditonally start the test. This runs the test in both `ant test` and `jython src/testcases/uk/ac/starlink/ttools/tabletest.py`.

**Comment by mbtaylor** [comment]
I made an additional commit13231e685c3  that defends against accidental non-invocation of the tests in future.

**Comment by olebole** [comment]
That may be misleading in the case that one uses f.e. `jython -m unittest discover` (available in [Python 2.7](https://docs.python.org/2/library/unittest.html#test-discovery); probably in Jython 2.7 as well), since then the file is imported as a module (`__name__ == 'tabletest'`). In that case, unittest would print the "Tests not run" warning but then run the tests. That may be a synthetic problem, however, since there is only one test (and so test discovery not really needed).

**Comment by mbtaylor** [comment]
OK well if you want to propose another solution go ahead, but as I commented earlier I do want some guard against the possibility that future changes to the test code inadvertently cause the tests to get skipped without warning, as happened in your earlier change.

**Comment by olebole** [comment]
The problem is IMO that the logic in `JyStiltsTest.java` and `tabletest.py` somehow tries to mimic the behaviour of the Jython `unittest` framework, but with the test discovery actually done in the test source. So, the best solution would probably be to run `java -jar jython.jar $testfile` with the appropriate classpath from ant instead. Using parts of one unit test framework within the other seems a probable cause for errors to me. The other solution would be to move the test discovery loop from the Python file(s) into `JyStiltsTest` and then to check whether the number of discovered tests is zero.

**Comment by mbtaylor** [comment]
Your analysis is probably correct, but I don't really want to add more complication to the build.xml file (2 types of test) and unless I'm missing something it would be hard to discover tests defined in python source code from a java testcase.

If this is actually doing what you need it to, and it is for me, I propose to leave it as it is.  But if you consider a further fix essential I can adjust the ant file.

**Comment by olebole** [comment]
In the moment (just one test case) I am fine here -- we should just keep that in mind. If the number of test files grow up, we can still extend.

**Pull request merged**
